
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Twin Peta
 */
public class AddNewBook extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    String query;
    String i;

    /**
     * Creates new form AddNewBook
     */
    public AddNewBook() {
        initComponents();
    }
    public void date(){
        Date now = new Date();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         i= sdf.format(now);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_BookId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_BookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmb_Program = new javax.swing.JComboBox<>();
        cmb_Essentials = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_Home = new javax.swing.JButton();
        btn$Issue = new javax.swing.JButton();
        btn_Returnbook = new javax.swing.JButton();
        btnBookDetails = new javax.swing.JButton();
        btn_bkDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_BookInfo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        label_Date = new javax.swing.JLabel();
        btn_Reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Print = new javax.swing.JMenuItem();
        menu_save = new javax.swing.JMenuItem();
        Menu_SaveAll = new javax.swing.JMenuItem();
        menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_Undo = new javax.swing.JMenuItem();
        menu_Redo = new javax.swing.JMenuItem();
        menu_cut = new javax.swing.JMenuItem();
        menu_Paste = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_Developer = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menu_BooksAdded = new javax.swing.JMenuItem();
        menu_Recentpage = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menu_AboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add  NewBook");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 102, -1, -1));

        txt_BookId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_BookIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_BookIdKeyTyped(evt);
            }
        });
        getContentPane().add(txt_BookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 100, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 157, -1, -1));

        txt_BookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_BookName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_BookNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_BookNameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 155, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Author");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 196, -1, -1));

        txt_Author.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Author.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AuthorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AuthorKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 194, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Program");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 248, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Essentials");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 301, -1, -1));

        btn_Add.setBackground(new java.awt.Color(0, 102, 102));
        btn_Add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        btn_Add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_AddKeyPressed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 116, -1));

        btnCancel.setBackground(new java.awt.Color(204, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 357, 104, -1));

        cmb_Program.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Program", "BBC", "BOIM", "BCOMM", "BSPM", "Entrepreneurship" }));
        cmb_Program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ProgramActionPerformed(evt);
            }
        });
        cmb_Program.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_ProgramKeyPressed(evt);
            }
        });
        getContentPane().add(cmb_Program, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 243, 160, -1));

        cmb_Essentials.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Essentials.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Essential" }));
        cmb_Essentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EssentialsActionPerformed(evt);
            }
        });
        cmb_Essentials.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_EssentialsKeyPressed(evt);
            }
        });
        getContentPane().add(cmb_Essentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 296, 160, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Add a New Book");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        btn_Home.setBackground(new java.awt.Color(0, 102, 102));
        btn_Home.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Home.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home.setText("Home");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        btn$Issue.setBackground(new java.awt.Color(0, 102, 102));
        btn$Issue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn$Issue.setForeground(new java.awt.Color(255, 255, 255));
        btn$Issue.setText("Issue Book");
        btn$Issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn$IssueActionPerformed(evt);
            }
        });
        getContentPane().add(btn$Issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        btn_Returnbook.setBackground(new java.awt.Color(0, 102, 102));
        btn_Returnbook.setForeground(new java.awt.Color(255, 255, 255));
        btn_Returnbook.setText("Return Book");
        btn_Returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        btnBookDetails.setBackground(new java.awt.Color(0, 102, 102));
        btnBookDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnBookDetails.setText("Issued Book Details");
        btnBookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        btn_bkDetails.setBackground(new java.awt.Color(0, 102, 102));
        btn_bkDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_bkDetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_bkDetails.setText("Book Details");
        btn_bkDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bkDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bkDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        txt_BookInfo.setColumns(20);
        txt_BookInfo.setRows(5);
        jScrollPane1.setViewportView(txt_BookInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 470, 280));

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, -1));

        label_Date.setBackground(new java.awt.Color(0, 0, 153));
        label_Date.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        label_Date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(label_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 180, 50));

        btn_Reset.setBackground(new java.awt.Color(0, 102, 102));
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lib.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -35, 880, 530));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        Menu_Print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_Print.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        Menu_Print.setText("Print");
        Menu_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PrintActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Print);

        menu_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_save.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_save.setText("Save");
        jMenu1.add(menu_save);

        Menu_SaveAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_SaveAll.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        Menu_SaveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a1.png"))); // NOI18N
        Menu_SaveAll.setText("Save All");
        Menu_SaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_SaveAllActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_SaveAll);

        menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_Exit.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        menu_Exit.setText("Exit");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        menu_Undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_Undo.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_Undo.setText("Undo");
        jMenu2.add(menu_Undo);

        menu_Redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_Redo.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_Redo.setText("Redo");
        jMenu2.add(menu_Redo);

        menu_cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_cut.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_cut.setText("Cut");
        jMenu2.add(menu_cut);

        menu_Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_Paste.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_Paste.setText("Paste");
        jMenu2.add(menu_Paste);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Team");
        jMenu3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        menu_Developer.setText("Developer Contact");
        menu_Developer.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem9.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jMenuItem9.setText("+256706866585");
        menu_Developer.add(jMenuItem9);

        jMenu3.add(menu_Developer);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Window");
        jMenu5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        menu_BooksAdded.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_BooksAdded.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_BooksAdded.setText("Books Added");
        jMenu5.add(menu_BooksAdded);

        menu_Recentpage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_Recentpage.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_Recentpage.setText("Recent page");
        jMenu5.add(menu_Recentpage);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Help");
        jMenu6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        menu_AboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_AboutUs.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        menu_AboutUs.setText("About us");
        jMenu6.add(menu_AboutUs);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_EssentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EssentialsActionPerformed
        
    }//GEN-LAST:event_cmb_EssentialsActionPerformed

    private void cmb_ProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ProgramActionPerformed
        if(cmb_Program.getSelectedItem()=="BBC")
        {
            cmb_Essentials.removeAllItems();
            cmb_Essentials.addItem("Select Essential");cmb_Essentials.addItem("Computerised Acc");cmb_Essentials.addItem("Systems Design");cmb_Essentials.addItem("Systems Modelling");
        }
        if(cmb_Program.getSelectedItem()=="BOIM")
        {
            cmb_Essentials.removeAllItems();
            cmb_Essentials.addItem("Select Essential");cmb_Essentials.addItem("Office Management");cmb_Essentials.addItem("Financial Mgt");cmb_Essentials.addItem("Secretarianism");
        }
        if(cmb_Program.getSelectedItem()=="BCOMM")
        {
            cmb_Essentials.removeAllItems();
            cmb_Essentials.addItem("Select Essential");cmb_Essentials.addItem("Accounting");cmb_Essentials.addItem("Marketing");cmb_Essentials.addItem("Production Management");
        }
         if(cmb_Program.getSelectedItem()=="BSPM")
        {
            cmb_Essentials.removeAllItems();
            cmb_Essentials.addItem("Select Essential");cmb_Essentials.addItem("Supply Mgt");cmb_Essentials.addItem("Purchase mgt");cmb_Essentials.addItem("Supply Chain");
        }
          if(cmb_Program.getSelectedItem()=="Entrepreneurship")
        {
            cmb_Essentials.removeAllItems();
            cmb_Essentials.addItem("Select Essential");cmb_Essentials.addItem("Business generation");cmb_Essentials.addItem("Conceptualised Ideas");cmb_Essentials.addItem("E-Commerce");
        }
    }//GEN-LAST:event_cmb_ProgramActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
       date();
        label_Date.setText(i);
        if(txt_BookId.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter Book id"); 
        else if(txt_BookName.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter Book name"); 
        else if(txt_BookName.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter author name"); 
        else if(cmb_Program.getSelectedItem().equals("Select Stream"))
            JOptionPane.showMessageDialog(this,"Please select stream");
        else if(cmb_Essentials.getSelectedItem().equals("Select Class"))
            JOptionPane.showMessageDialog(this,"Please select class");    
        else
        {
        try
        {
        connect();
        query="insert into books values('"+txt_BookId.getText()+"','"+txt_BookName.getText()+"','"+txt_Author.getText()+"','"+cmb_Program.getSelectedItem()+"','"+cmb_Essentials.getSelectedItem()+"');";
        stmt.executeUpdate(query);
        
        disconnect();
        JOptionPane.showMessageDialog(this,"New book added to Library");
        txt_BookInfo.append("The following are the book details recoreded into the database:"
        +"\n BookId is :" +txt_BookId.getText()+"\n Book Name is :"+txt_BookName.getText()
       +"\n Book Author is :"+txt_Author.getText()+"\n Selected Program is "+cmb_Program.getSelectedItem()
       +"\n Selected Essential is: "+cmb_Essentials.getSelectedItem());
        txt_BookId.setText("");
        txt_BookName.setText("");
        txt_Author.setText("");
        cmb_Program.setSelectedIndex(0);
        cmb_Essentials.removeAllItems();
        cmb_Essentials.addItem("Select Essential");
        
        }
        catch(SQLException e)
        {
            if(e.getErrorCode()==1062)
                JOptionPane.showMessageDialog(this,"BookId is a primary key\nduplicate entry is not allowed\nit should be unique");
            else
                JOptionPane.showMessageDialog(this,"connection error");
        }
                }
       
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn$IssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn$IssueActionPerformed
        IssueBook ib=new IssueBook();
        ib.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn$IssueActionPerformed

    private void btn_ReturnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnbookActionPerformed
        ReturnBook rb=new ReturnBook();
        rb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ReturnbookActionPerformed

    private void btnBookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookDetailsActionPerformed
        IssuedBooks ibs=new IssuedBooks();
        ibs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookDetailsActionPerformed

    private void btn_bkDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bkDetailsActionPerformed
        BookDetails bd=new BookDetails();
        bd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_bkDetailsActionPerformed

    private void Menu_SaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SaveAllActionPerformed
       
    }//GEN-LAST:event_Menu_SaveAllActionPerformed

    private void Menu_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PrintActionPerformed

        try {
            txt_BookInfo.print();
        } catch (PrinterException ex) {
            Logger.getLogger(AddNewBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Menu_PrintActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        txt_BookInfo.setText("");
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
     if(JOptionPane.showConfirmDialog(null,"Confirm if you want to exit", "Quit",
              JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
          System.exit(0);
} else {
}
{
       
    }
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void txt_BookIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BookIdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txt_BookName.requestFocus();
        }
    }//GEN-LAST:event_txt_BookIdKeyPressed

    private void txt_BookNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BookNameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txt_Author.requestFocus();
        }
    }//GEN-LAST:event_txt_BookNameKeyPressed

    private void txt_AuthorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AuthorKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cmb_Program.requestFocus();
       }
    }//GEN-LAST:event_txt_AuthorKeyPressed

    private void cmb_ProgramKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_ProgramKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cmb_Essentials.requestFocus();
        }
    }//GEN-LAST:event_cmb_ProgramKeyPressed

    private void cmb_EssentialsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_EssentialsKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_Add.requestFocus();
       }
    }//GEN-LAST:event_cmb_EssentialsKeyPressed

    private void btn_AddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_AddKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txt_BookId.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter Book id"); 
        else if(txt_BookName.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter Book name"); 
        else if(txt_BookName.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please enter author name"); 
        else if(cmb_Program.getSelectedItem().equals("Select Program"))
            JOptionPane.showMessageDialog(this,"Please select Program you do");
        else if(cmb_Essentials.getSelectedItem().equals("Select Essentials"))
            JOptionPane.showMessageDialog(this,"Please select Essentials");    
        else
        {
        try
        {
        connect();
        query="insert into books values('"+txt_BookId.getText()+"','"+txt_BookName.getText()+"','"+txt_Author.getText()+"','"+cmb_Program.getSelectedItem()+"','"+cmb_Essentials.getSelectedItem()+"','');";
        stmt.executeUpdate(query);
        
        disconnect();
        JOptionPane.showMessageDialog(this,"New book added to Library");
        txt_BookInfo.append("The following are the book details recoreded into the database:"
        +"\n BookId is :" +txt_BookId.getText()+"\n Book Name is :"+txt_BookName.getText()
       +"\n Book Author is :"+txt_Author.getText()+"\n Selected Program is "+cmb_Program.getSelectedItem()
       +"\n Selected Essential is: "+cmb_Essentials.getSelectedItem());
        txt_BookId.setText("");
        txt_BookName.setText("");
        txt_Author.setText("");
        cmb_Program.setSelectedIndex(0);
        cmb_Essentials.removeAllItems();
        cmb_Essentials.addItem("Select Select Essentials");
        
        }
        catch(SQLException e)
        {
            if(e.getErrorCode()==1062)
                JOptionPane.showMessageDialog(this,"BookId is a primary key\nduplicate entry is not allowed\nit should be unique");
            else
                JOptionPane.showMessageDialog(this,"Connection error");
        }
                }
        }
    }//GEN-LAST:event_btn_AddKeyPressed

    private void txt_BookNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BookNameKeyTyped
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){ 
            JOptionPane.showMessageDialog(null, "Please input text only and not numbers");
           evt.consume();}
    }//GEN-LAST:event_txt_BookNameKeyTyped

    private void txt_BookIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BookIdKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){ 
             JOptionPane.showMessageDialog(null, "Please input numbers only and not text");
           evt.consume();}
    }//GEN-LAST:event_txt_BookIdKeyTyped

    private void txt_AuthorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AuthorKeyTyped
       char c = evt.getKeyChar();
        if(Character.isDigit(c)){ 
            JOptionPane.showMessageDialog(null, "Please input text only and not numbers");
           evt.consume();}
    }//GEN-LAST:event_txt_AuthorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewBook().setVisible(true);
            }
        });
    }

    public void connect()
    {
        try
        {  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/books","root","");  
            stmt=con.createStatement(); 
        }
        catch(ClassNotFoundException | SQLException e)
        { 
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"connection error");
        }
    }
    public void disconnect()
    {
        try
        {
           con.close(); 
        }
        catch(SQLException e)
        {}

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Print;
    private javax.swing.JMenuItem Menu_SaveAll;
    private javax.swing.JButton btn$Issue;
    private javax.swing.JButton btnBookDetails;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Returnbook;
    private javax.swing.JButton btn_bkDetails;
    private javax.swing.JComboBox<String> cmb_Essentials;
    private javax.swing.JComboBox<String> cmb_Program;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Date;
    private javax.swing.JMenuItem menu_AboutUs;
    private javax.swing.JMenuItem menu_BooksAdded;
    private javax.swing.JMenu menu_Developer;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JMenuItem menu_Paste;
    private javax.swing.JMenuItem menu_Recentpage;
    private javax.swing.JMenuItem menu_Redo;
    private javax.swing.JMenuItem menu_Undo;
    private javax.swing.JMenuItem menu_cut;
    private javax.swing.JMenuItem menu_save;
    private javax.swing.JTextField txt_Author;
    private javax.swing.JTextField txt_BookId;
    private javax.swing.JTextArea txt_BookInfo;
    private javax.swing.JTextField txt_BookName;
    // End of variables declaration//GEN-END:variables
}
