
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Twin Peta
 */
public class BookDetails extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    String query;
    String BId,Bname,Bauthor,strm,cls,avl;
    /**
     * Creates new form BookDetails
     */
    public BookDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.ButtonGroup();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        Search_byProgram = new javax.swing.JComboBox<>();
        cmb_SelectEssential = new javax.swing.JComboBox<>();
        txtSearchBook_ByName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Information_Table = new javax.swing.JTable();
        Add_A_New_Book = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Issue_Book = new javax.swing.JButton();
        Return_Book = new javax.swing.JButton();
        Issued_Book_Details = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        r1.setText("Search by Book Name");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 118, -1, -1));

        b1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        r2.setText("Search By Essential");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 165, -1, -1));

        Search_byProgram.setForeground(new java.awt.Color(204, 0, 0));
        Search_byProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Program", "BBC", "BOIM", "BPSM", "Entrepreneurship", " " }));
        Search_byProgram.setEnabled(false);
        Search_byProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_byProgramActionPerformed(evt);
            }
        });
        getContentPane().add(Search_byProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 160, 185, 29));

        cmb_SelectEssential.setForeground(new java.awt.Color(204, 0, 0));
        cmb_SelectEssential.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Essential" }));
        cmb_SelectEssential.setEnabled(false);
        cmb_SelectEssential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_SelectEssentialActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_SelectEssential, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 160, 155, 29));

        txtSearchBook_ByName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSearchBook_ByName.setForeground(new java.awt.Color(204, 0, 0));
        txtSearchBook_ByName.setEnabled(false);
        txtSearchBook_ByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBook_ByNameActionPerformed(evt);
            }
        });
        txtSearchBook_ByName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBook_ByNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearchBook_ByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 118, 185, -1));

        Information_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author", "Program", "Essential", "Available"
            }
        ));
        Information_Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(Information_Table);
        if (Information_Table.getColumnModel().getColumnCount() > 0) {
            Information_Table.getColumnModel().getColumn(0).setPreferredWidth(40);
            Information_Table.getColumnModel().getColumn(1).setPreferredWidth(210);
            Information_Table.getColumnModel().getColumn(2).setPreferredWidth(150);
            Information_Table.getColumnModel().getColumn(3).setPreferredWidth(40);
            Information_Table.getColumnModel().getColumn(4).setPreferredWidth(40);
            Information_Table.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 215, 778, 262));

        Add_A_New_Book.setBackground(new java.awt.Color(0, 102, 102));
        Add_A_New_Book.setForeground(new java.awt.Color(255, 255, 255));
        Add_A_New_Book.setText("Add a  New Book ");
        Add_A_New_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_A_New_BookActionPerformed(evt);
            }
        });
        getContentPane().add(Add_A_New_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 116, 160, 26));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 94, -1));

        Issue_Book.setBackground(new java.awt.Color(0, 102, 102));
        Issue_Book.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Issue_Book.setForeground(new java.awt.Color(255, 255, 255));
        Issue_Book.setText("Issue Book");
        Issue_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Issue_BookActionPerformed(evt);
            }
        });
        getContentPane().add(Issue_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 105, -1));

        Return_Book.setBackground(new java.awt.Color(0, 102, 102));
        Return_Book.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Return_Book.setForeground(new java.awt.Color(255, 255, 255));
        Return_Book.setText("Return Book");
        Return_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_BookActionPerformed(evt);
            }
        });
        getContentPane().add(Return_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        Issued_Book_Details.setBackground(new java.awt.Color(0, 102, 102));
        Issued_Book_Details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Issued_Book_Details.setForeground(new java.awt.Color(255, 255, 255));
        Issued_Book_Details.setText("Issued Book Details");
        Issued_Book_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Issued_Book_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Issued_Book_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Book Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 19, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        Search_byProgram.disable();cmb_SelectEssential.disable();
        txtSearchBook_ByName.enable();
    }//GEN-LAST:event_r1ActionPerformed

    private void txtSearchBook_ByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBook_ByNameActionPerformed
        
    }//GEN-LAST:event_txtSearchBook_ByNameActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        txtSearchBook_ByName.disable();
        Search_byProgram.enable();
    }//GEN-LAST:event_r2ActionPerformed

    private void cmb_SelectEssentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_SelectEssentialActionPerformed
        try
        {
           
        connect();
        query="select * from books where Program='"+Search_byProgram.getSelectedItem()+"' and Essential='"+cmb_SelectEssential.getSelectedItem()+"';";
        rs=stmt.executeQuery(query); 
        DefaultTableModel model=(DefaultTableModel)Information_Table.getModel();
        model.setRowCount(0);
        while(rs.next())
        {
            BId=rs.getString("BookID");
            Bname=rs.getString("Book Name");
            Bauthor=rs.getString("Author");
            strm=rs.getString("Program");
            cls=rs.getString("Essential");
            avl=rs.getString("Available");
            Object[] row = {BId,Bname,Bauthor,strm,cls,avl};
            model.addRow(row);
        }
        disconnect();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_cmb_SelectEssentialActionPerformed

    private void Search_byProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_byProgramActionPerformed
        cmb_SelectEssential.enable();
        if(Search_byProgram.getSelectedItem()=="BBC")
        {
            cmb_SelectEssential.removeAllItems();
            cmb_SelectEssential.addItem("Select Essential");cmb_SelectEssential.addItem("Computerised Acc");cmb_SelectEssential.addItem("Systems Design");cmb_SelectEssential.addItem("Systems Analysis");
        }
        if(Search_byProgram.getSelectedItem()=="BOIM")
        {
            cmb_SelectEssential.removeAllItems();
            cmb_SelectEssential.addItem("Select Essential");cmb_SelectEssential.addItem("Office Mgt");cmb_SelectEssential.addItem("Financial Mgt");cmb_SelectEssential.addItem("Secretarianism");
        }
        if(Search_byProgram.getSelectedItem()=="BCOMM")
        {
            cmb_SelectEssential.removeAllItems();
            cmb_SelectEssential.addItem("Select Essential");cmb_SelectEssential.addItem("Accounting");cmb_SelectEssential.addItem("Marketing");cmb_SelectEssential.addItem("Production Mgt");
        }
        if(Search_byProgram.getSelectedItem()=="BPSM")
        {
            cmb_SelectEssential.removeAllItems();
            cmb_SelectEssential.addItem("Select Essential");cmb_SelectEssential.addItem("Supply Mgt");cmb_SelectEssential.addItem("Purchase Mgt");cmb_SelectEssential.addItem("Supply Chain");
        }
        if(Search_byProgram.getSelectedItem()=="Entrepreneurship")
        {
            cmb_SelectEssential.removeAllItems();
            cmb_SelectEssential.addItem("Select Essential");cmb_SelectEssential.addItem("Business generation ");cmb_SelectEssential.addItem("Conceptualised Ideas");cmb_SelectEssential.addItem("E-Commerce");
        }
    }//GEN-LAST:event_Search_byProgramActionPerformed

    private void txtSearchBook_ByNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBook_ByNameKeyReleased
        DefaultTableModel model=(DefaultTableModel)Information_Table.getModel();
        model.setRowCount(0);
        String txt=txtSearchBook_ByName.getText();
        if(txt.equals(""))
            System.out.println("");
        else
        {
            try
            {
                connect();
                query="select * from books where Book Name LIKE \"%"+txtSearchBook_ByName.getText()+"%\"yes";
                rs=stmt.executeQuery(query); 
                while(rs.next())
                {
                    BId=rs.getString("BookID");
                    Bname=rs.getString("Book Name");
                    Bauthor=rs.getString("Author");
                    strm=rs.getString("Program");
                    cls=rs.getString("Essential");
                    avl=rs.getString("Available");
                    Object[] row = {BId,Bname,Bauthor,strm,cls,avl};
                    model.addRow(row);
                }
                disconnect();
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
        }   
    }//GEN-LAST:event_txtSearchBook_ByNameKeyReleased

    private void Add_A_New_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_A_New_BookActionPerformed
        AddNewBook anb=new AddNewBook();
        anb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_A_New_BookActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Issue_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Issue_BookActionPerformed
        IssueBook ib=new IssueBook();
        ib.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Issue_BookActionPerformed

    private void Return_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_BookActionPerformed
        ReturnBook rb=new ReturnBook();
        rb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Return_BookActionPerformed

    private void Issued_Book_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Issued_Book_DetailsActionPerformed
        IssuedBooks ibs=new IssuedBooks();
        ibs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Issued_Book_DetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BookDetails().setVisible(true);
        });
    }
    public void connect()
    {
        try
        {  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/books","root","");  
            stmt=con.createStatement(); 
        }
        catch(ClassNotFoundException | SQLException e)
        { 
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"connection error");
        }
    }
    public void disconnect()
    {
        try
        {
           con.close(); 
        }
        catch(SQLException e)
        {}

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_A_New_Book;
    private javax.swing.JTable Information_Table;
    private javax.swing.JButton Issue_Book;
    private javax.swing.JButton Issued_Book_Details;
    private javax.swing.JButton Return_Book;
    private javax.swing.JComboBox<String> Search_byProgram;
    private javax.swing.ButtonGroup b1;
    private javax.swing.JComboBox<String> cmb_SelectEssential;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField txtSearchBook_ByName;
    // End of variables declaration//GEN-END:variables
}
